code --install-extension andrejunges.Handlebars
code --install-extension aprilandjan.ascii-tree-generator
code --install-extension asvetliakov.vscode-neovim
code --install-extension ban.spellright
code --install-extension brainfit.vscode-coverage-highlighter
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension brunnerh.insert-unicode
code --install-extension bungcip.better-toml
code --install-extension dbaeumer.vscode-eslint
code --install-extension dberezin.lox-language
code --install-extension debugpig.highlight
code --install-extension elmTooling.elm-ls-vscode
code --install-extension esbenp.prettier-vscode
code --install-extension foam.foam-vscode
code --install-extension GraphQL.vscode-graphql
code --install-extension Gruntfuggly.todo-tree
code --install-extension hbenl.vscode-test-explorer
code --install-extension hoovercj.vscode-settings-cycler
code --install-extension humao.rest-client
code --install-extension Huuums.vscode-fast-folder-structure
code --install-extension jacobdufault.fuzzy-search
code --install-extension jeff-hykin.mario
code --install-extension johnpapa.vscode-peacock
code --install-extension karigari.chat
code --install-extension lfs.vscode-emacs-friendly
code --install-extension lucax88x.codeacejumper
code --install-extension mathiasfrohlich.Kotlin
code --install-extension mhutchie.git-graph
code --install-extension mksafi.find-jump
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mushan.vscode-paste-image
code --install-extension naumovs.color-highlight
code --install-extension nwolverson.language-purescript
code --install-extension Orta.vscode-jest
code --install-extension Orta.vscode-react-native-storybooks
code --install-extension redhat.java
code --install-extension rust-lang.rust
code --install-extension sendhil.vscode-file-explorer-menu
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shuworks.vscode-jump-to-hint
code --install-extension skattyadz.vscode-quick-scope
code --install-extension teamchilla.blueprint
code --install-extension tomoki1207.pdf
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscodeemacs.emacs
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame
code --install-extension waldemard.vscode-emacs-hjkl
code --install-extension wmaurer.vscode-jumpy
code --install-extension yzhang.markdown-all-in-one
code --install-extension zjhmale.vscode-ag
